/**
 * Regenerates src/lib/data/topo-lines.ts from the stroke version of the
 * topographic pattern in src/components/topo-bg.svelte.
 *
 * The source artwork is a single path with one closed subpath per contour
 * line, designed as a 600x600 repeating tile. Contours clipped at the tile
 * edge are closed by tracing straight segments along the border; invisible
 * when filled, but stroked they show up as straight lines at every tile
 * seam. This script splits the path into one absolute-coordinate d string
 * per contour, cutting each contour at those edge runs and dropping them.
 *
 * svg-pathdata is not a project dependency. Run with:
 *   bun --install=fallback run scripts/generate-topo-lines.ts
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { SVGPathData } from 'svg-pathdata';

const TILE = 600;
const EPS = 0.25;

const source = readFileSync(new URL('../src/components/topo-bg.svelte', import.meta.url), 'utf8');
const match = source.match(/\bd="([^"]+)"/);
if (!match) throw new Error('No path data found in topo-bg.svelte');

const abs = new SVGPathData(match[1]).toAbs();

type Cmd = (typeof abs.commands)[number];

const subpaths: Cmd[][] = [];
let current: Cmd[] = [];
for (const cmd of abs.commands) {
	if (cmd.type === SVGPathData.MOVE_TO && current.length) {
		subpaths.push(current);
		current = [];
	}
	current.push(cmd);
}
if (current.length) subpaths.push(current);

function onSameEdge(a: { x: number; y: number }, b: { x: number; y: number }) {
	return (
		(Math.abs(a.x) < EPS && Math.abs(b.x) < EPS) ||
		(Math.abs(a.x - TILE) < EPS && Math.abs(b.x - TILE) < EPS) ||
		(Math.abs(a.y) < EPS && Math.abs(b.y) < EPS) ||
		(Math.abs(a.y - TILE) < EPS && Math.abs(b.y - TILE) < EPS)
	);
}

const STRAIGHT = new Set<number>([
	SVGPathData.LINE_TO,
	SVGPathData.HORIZ_LINE_TO,
	SVGPathData.VERT_LINE_TO,
	SVGPathData.CLOSE_PATH
]);

let edgeRunsDropped = 0;
const pieces: Cmd[][] = [];

for (const cmds of subpaths) {
	const start = cmds[0] as { x: number; y: number };
	let prev = { x: start.x, y: start.y };
	let piece: Cmd[] = [cmds[0]];
	const flush = () => {
		if (piece.length > 1) pieces.push(piece);
	};
	for (const cmd of cmds.slice(1)) {
		const end =
			cmd.type === SVGPathData.CLOSE_PATH
				? { x: start.x, y: start.y }
				: {
						x: 'x' in cmd && typeof cmd.x === 'number' ? cmd.x : prev.x,
						y: 'y' in cmd && typeof cmd.y === 'number' ? cmd.y : prev.y
					};
		if (STRAIGHT.has(cmd.type) && onSameEdge(prev, end)) {
			edgeRunsDropped++;
			flush();
			piece = [{ type: SVGPathData.MOVE_TO, relative: false, x: end.x, y: end.y } as Cmd];
		} else {
			piece.push(cmd);
		}
		prev = end;
	}
	flush();
}

const ds = pieces.map((cmds) => new SVGPathData(cmds).round(100).encode());

console.log('contours:', subpaths.length);
console.log('edge runs dropped:', edgeRunsDropped, '-> pieces:', ds.length);

const body = ds.map((s) => `\t'${s}'`).join(',\n');
const out = `// Generated by scripts/generate-topo-lines.ts. Do not edit by hand.
// One path per topographic contour line, absolute coordinates, designed
// for a 600x600 repeating tile (same artwork as /images/blue-topo.svg).

export const TOPO_TILE_SIZE = 600;

export const topoLines: string[] = [
${body}
];
`;
writeFileSync(new URL('../src/lib/data/topo-lines.ts', import.meta.url), out);
console.log('written: src/lib/data/topo-lines.ts');
